# Generated by Django 4.2.20 on 2025-06-20 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0008_alter_advert_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('external_transaction_id', models.CharField(max_length=128, verbose_name='ID внешней транзакции')),
                (
                    'status',
                    models.CharField(
                        choices=[('ERR', 'ошибка'), ('PND', 'в процессе'), ('SUC', 'успешен'), ('CAN', 'отменен')],
                        default='PND',
                        max_length=16,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'service_provider',
                    models.CharField(choices=[('YOO_KASSA', 'ЮКасса')], default='YOO_KASSA', verbose_name='Провайдер'),
                ),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                (
                    'advert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='promotion_payments',
                        to='booking.advert',
                        verbose_name='Объявление',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='payments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
