repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
    -   id: mypy
        additional_dependencies:
            - django-stubs
            - djangorestframework-stubs

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
        - id: black
          args:
              - --line-length=120
              - --check
              - --diff
              - --color
          exclude: ^.*\b(migrations)\b.*$

-   repo: local
    hooks:
        - id: pytest
          name: pytest
          entry: bash -c './Taskfile.sh test'
          language: system
