x-postgres-db-variables: &db-variables
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: adminpassword
  POSTGRES_DB: booking_platform
x-postgres-admin-variables: &pgadmin-variables
  PGADMIN_DEFAULT_EMAIL: admin@mail.store
  PGADMIN_DEFAULT_PASSWORD: adminpassword
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment: *db-variables
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment: *pgadmin-variables
    ports:
      - "5050:80"
    depends_on:
      - postgres