services:
  caddy:
    image: caddy:2.6-alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./.docker/caddy-config:/config
      - ./.docker/caddy-data:/data
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
