services:
  caddy:
    image: caddy:2.6-alpine
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${SERVER_PATH:.}/static:/var/www/django/static
      - ${SERVER_PATH:.}/media:/var/www/django/media
      - ./.docker/caddy-config:/config
      - ./.docker/caddy-data:/data
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
