# Generated by Django 4.2.20 on 2025-06-19 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема обращения')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решено')),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='support_messages',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Сообщение в поддержку',
                'verbose_name_plural': 'Сообщения в поддержку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                (
                    'agent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='suport_answers',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Агент поддержки',
                    ),
                ),
                (
                    'message',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='answers',
                        to='support.supportmessage',
                        verbose_name='Обращение',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ответ поддержки',
                'verbose_name_plural': 'Ответы поддержки',
                'ordering': ['-created_at'],
            },
        ),
    ]
