# Generated by Django 5.1.6 on 2025-02-25 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '__first__'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='is_active',
        ),
        migrations.AddField(
            model_name='advert',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='authentication.profile', verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='advert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активировано'), ('DISABLED', 'Не опубликовано')], default='DISABLED', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='activated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Активировано'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='promotion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advert', to='booking.promotion', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
