# Generated by Django 4.2.19 on 2025-02-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_advert_is_active_advert_contact_advert_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='promotion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advert', to='booking.promotion', verbose_name='Продвижение'),
        ),
    ]
