# Generated by Django 4.2.19 on 2025-02-26 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('booking', '0003_alter_advert_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активировано'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='contact',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='authentication.profile', verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='promotion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advert', to='booking.promotion', verbose_name='Продвижение'),
        ),
    ]
