# Generated by Django 5.1.6 on 2025-02-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_advert_activated_at_alter_advert_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активно'), ('DISABLED', 'Отключено')], default='DISABLED', max_length=16, verbose_name='Статус'),
        ),
    ]
