# Generated by Django 4.2.20 on 2025-04-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_promotion_created_at_promotion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активно до'),
        ),
        migrations.AddField(
            model_name='advert',
            name='location',
            field=models.CharField(default='Неизвестно', max_length=255, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='advert',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Уровень продвижения'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип | Описание продвижения'),
        ),
    ]
