# Generated by Django 4.2.20 on 2025-04-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_advert_active_until_advert_location_advert_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
