# Generated by Django 4.2.20 on 2025-05-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_advert_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.CharField(
                choices=[('ACTIVE', 'Активировано'), ('DISABLED', 'Не опубликовано'), ('DRAFT', 'Черновик')],
                default='DISABLED',
                max_length=16,
                verbose_name='Статус',
            ),
        ),
    ]
