# Generated by Django 4.2.20 on 2025-05-09 16:17

import DjangoServer.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_advert_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='adverts/images/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='status',
            field=models.CharField(
                choices=[('ACTIVE', 'Активировано'), ('DISABLED', 'Не опубликовано'), ('DRAFT', 'Черновик')],
                default='DISABLED',
                max_length=16,
                verbose_name='Статус',
            ),
        ),
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=DjangoServer.utils.user_directory_path)),
                (
                    'advert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='images',
                        to='booking.advert',
                        verbose_name='Объявление',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Фотография объявления',
                'verbose_name_plural': 'Фотографии объявлений',
            },
        ),
    ]
