# Generated by Django 4.2.20 on 2025-06-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_advert_logo_alter_advert_status_advertimage'),
        ('booking', '0008_alter_advert_status'),
    ]

    operations = []
