# Generated by Django 4.2.20 on 2025-06-22 17:04

import DjangoServer.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_merge_20250622_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='logo',
            field=models.ImageField(
                blank=True, null=True, upload_to=DjangoServer.utils.user_directory_path, verbose_name='Логотип'
            ),
        ),
    ]
