# Generated by Django 4.2.20 on 2025-05-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_rate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('profile', 'author'), name='unique_profile_author_pair'),
        ),
    ]
