# Generated by Django 4.2.20 on 2025-04-16 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_advert_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_profile_is_verified_onetimepassword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimepassword',
            options={'verbose_name': 'Одноразовый код', 'verbose_name_plural': 'Одноразовые коды'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_adverts',
            field=models.ManyToManyField(
                related_name='users_likes', to='booking.advert', verbose_name='Понравившиеся объявления'
            ),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='code',
            field=models.CharField(default='', max_length=128, verbose_name='Одноразовый код (хэш)'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='otps',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(
                choices=[('IND', 'Частное лицо'), ('CMP', 'Компания')],
                default='IND',
                max_length=3,
                verbose_name='Тип профиля',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='profile',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
    ]
