# Generated by Django 4.2.20 on 2025-05-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(
                choices=[('IND', 'Частное лицо'), ('CMP', 'Компания'), ('MOD', 'Модератор')],
                default='IND',
                max_length=3,
                verbose_name='Тип профиля',
            ),
        ),
    ]
