name: deploy

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy via SSH with Docker Compose
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          BRANCH=${{ github.ref_name }}

          if [[ $BRANCH = ${{ secrets.STAGE_BRANCH }} || $BRANCH = configure/deploy ]]; then
            SERVER=${{ secrets.STAGE_SERVER }}
            PROJECT_DIR=/srv/projects/Django-Server/Django-Server/Django-Server
            cd $PROJECT_DIR
          elif [ $BRANCH = ${{ secrets.PROD_BRANCH }} ]; then
            SERVER=${{ secrets.PROD_SERVER }}
            PROJECT_DIR=/home/user/prod/my-django-app
            cd $PROJECT_DIR
          else
            echo "Unknown branch: $BRANCH"
            exit 1
          fi
          
          ./Taskfile.sh rebuild
