name: deploy

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy via SSH with Docker Compose
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          BRANCH=${{ github.ref_name }}
          
          echo "STAGE_SERVER: ${{ secrets.STAGE_SERVER }}"
          echo "PROD_SERVER: ${{ secrets.PROD_SERVER }}"

          if [ "$BRANCH" = ${{ secrets.STAGE_BRANCH }} ]; then
            SERVER=${{ secrets.STAGE_SERVER }}
            PROJECT_DIR=/srv/projects/Django-Server
          elif [ "$BRANCH" = ${{ secrets.PROD_BRANCH }} ]; then
            SERVER=${{ secrets.PROD_SERVER }}
            PROJECT_DIR=/home/user/prod/my-django-app
          else
            echo "Unknown branch: $BRANCH"
            exit 1
          fi

          ssh -o StrictHostKeyChecking=no $SERVER << EOF
            set -e

            cd $PROJECT_DIR
            git pull origin $BRANCH

            ./Taskfile rebuild
          EOF
