name: lint

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.15"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run Ruff
        run: ruff check --output-format=github .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.15"
      - name: Install dependencies
        run: pip install mypy djangorestframework-types==0.8.0 django-stubs==5.1.3
      - name: Run mypy
        run: mypy . --disable-error-code='var-annotated' --disable-error-code='import-untyped' --disable-error-code='import-not-found' --exclude 'DjangoServer/__init__.py$'
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --diff --color --skip-string-normalization --line-length=120 --exclude=/migrations/"
          version: "~= 22.0"
